# Generated by Django 3.0.8 on 2020-09-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usurio_salida',
            new_name='Usuario_salida',
        ),
    ]
